#此端口是tomcat服务的端口
server:
  port: 8080
spring:
  discovery:
    serviceName: netty-server
#zookeeper注册地址
#registry.address=192.168.245.131:2181,192.168.245.131:2182,192.168.245.131:2183
registry:
  address:  127.0.0.1:2181
#RPC服务提供者地址 18001是netty服务的端口
rpc:
  server:
    address:  127.0.0.1:18001

zk:
  root:
    node: rpc,USER-INFO

